import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { publicSans } from "./lib/fonts";
import logo from "./assets/logo.png";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${publicSans.className} bg-white`}>{children}</body>
    </html>
  );
}
